### ISSUE TITLE
Unauthorized Select Access to Other User's Transaction Data

### ISSUE THREAD

**Issue by Krish-Das** [theKrishDas/project-nought-2024#7]
# Issue: Unauthorized Select Access to Other User's Transaction Data

## Description
There is a security vulnerability in the application that allows a user to view transaction data belonging to different users. This issue poses a significant privacy concern and needs to be addressed quickly.

## Expected Behavior
Users should only be able to access and view their own transaction data. Attempts to access other users' data should be restricted and result in an appropriate error response or redirection.

### Steps to Reproduce
1. Log in as a User.
2. Access the root('/') page or navigate to a transaction details page.

### Actual Result
User A can view transaction data belonging to another User.

### Expected Result
Accessing transaction data belonging to other users should result redirection to the user's own data.

**Comment by Krish-Das** [comment]
We are aware of the reported issue where users can view other user's transaction data. Please note that this behavior is intentional and currently in place for **development simplicity** as the application is still in its development phase.

Rest assured, we have plans to implement robust authentication and authorization mechanisms to ensure users can only access their own data.

**Comment by theKrishDas** [comment]
We have fixed the issue. Now users can view, edit and delete only their transactions.
